repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.0
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/PyCQA/pycodestyle
    rev: 2.12.1
    hooks:
      - id: pycodestyle
        args: [--config=.pycodestyle]
        files: ^backend/.*\.py$
