volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
  backend:
    image: dariiyak/kittygram_backend:latest
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      mkdir -p /backend_static/static &&
      cp -r /app/collected_static/. /backend_static/static/ &&
      gunicorn --bind 0.0.0.0:8000 kittygram_backend.wsgi"
  frontend:
    image: dariiyak/kittygram_frontend:latest
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
  gateway:
    image: dariiyak/kittygram_gateway:latest
    ports:
      - 9000:80
    volumes:
      - static:/static:ro
      - media:/media:ro
    depends_on:
      - backend
      - frontend
